# Generated by Django 4.0.3 on 2022-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_sensor_id_measurment_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurment',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
